import {createClient} from 'npm:@supabase/supabase-js@2';
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Content-Type':'application/json'};
const projectUrl=Deno.env.get('SUPABASE_URL')!;
const publishableKeys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')!);
const secretKeys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')!);
const authClient=createClient(projectUrl,publishableKeys.default);
const adminClient=createClient(projectUrl,secretKeys.default,{auth:{autoRefreshToken:false,persistSession:false}});
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:corsHeaders});
async function requireAdmin(req:Request){const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)throw new Error('Não autenticado.');const {data:{user},error}=await authClient.auth.getUser(token);if(error||!user)throw new Error('Sessão inválida.');const {data:profile}=await adminClient.from('profiles').select('role').eq('id',user.id).maybeSingle();if(profile?.role!=='admin')throw new Error('Acesso administrativo necessário.')}
function randomToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{await requireAdmin(req);const {slug}=await req.json();if(typeof slug!=='string'||!slug)return reply({error:'Cliente inválido.'},400);const {data:client,error:clientError}=await adminClient.from('clients').select('id,slug').eq('slug',slug).maybeSingle();if(clientError||!client)return reply({error:'Cliente não encontrado.'},404);const {data:existing,error:existingError}=await adminClient.from('dashboard_share_links').select('token').eq('client_id',client.id).eq('active',true).maybeSingle();if(existingError)throw existingError;if(existing)return reply({token:existing.token,slug:client.slug});const token=randomToken();const {error:insertError}=await adminClient.from('dashboard_share_links').insert({client_id:client.id,token});if(insertError)throw insertError;return reply({token,slug:client.slug},201)}catch(error){return reply({error:error instanceof Error?error.message:'Erro inesperado.'},400)}});
